driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 4096
  synced_folders:
    - ['..', '/home/vagrant/chef-server']
#    - ['../../omnibus', '/home/vagrant/omnibus']
# ['../../omnibus-software', '/home/vagrant/omnibus-software']
# TODO - zip dependency! package must be installed!
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.7.2

platforms:
  - name: ubuntu-16.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: centos-5.10
  - name: centos-6.5
  - name: centos-7.2
    run_list:  yum-epel::default

suites:
  - name: default
    attributes:
      omnibus:
        build_user: vagrant
        build_user_group: vagrant
        build_user_password: vagrant
        install_dir: /opt/opscode
    run_list: omnibus::default
